language: node_js

node_js:
- '7'
- '6'
- '5'
- '4'

matrix:
  fast_finish: true

sudo: false

deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
  on:
      all_branches: true
      tags: true
      repo: steeplejack-js/socketio

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d048e712b735c6cb4cf2
    on_success: change
    on_failure: always
    on_start: false
